 sonar.organization=corke123
sonar.projectKey=Corke123_trackly

sonar.sources=infra,.github,local,docker-compose.yaml,board-service/Dockerfile,gateway-service/Dockerfile,identity-service/Dockerfile,notification-service/Dockerfile
