create table activity
(
    id          bigint generated by default as identity primary key,
    event_id    varchar(100) unique,
    board_id    bigint,
    type        varchar(50)  not null,
    summary     varchar(500) not null,
    actor_id    varchar(100),
    occurred_at timestamptz  not null,
    recorded_at timestamptz  not null
);

create index idx_activity_board_time on activity (board_id, occurred_at desc);
