create table board
(
    id   bigint generated by default as identity primary key,
    name varchar(200) not null
);

create table swimlane
(
    id       bigint generated by default as identity primary key,
    board_id bigint       not null references board (id) on delete cascade,
    title    varchar(200) not null,
    position int          not null
);

create index idx_swimlane_board on swimlane (board_id);

create table ticket
(
    id          bigint generated by default as identity primary key,
    board_id    bigint       not null,
    swimlane_id bigint       not null,
    title       varchar(200) not null,
    description text,
    assignee_id varchar(100),
    position    int          not null,
    created_at  timestamptz  not null
);

create index idx_ticket_board on ticket (board_id);