create table outbox
(
    id             bigint generated by default as identity primary key,
    aggregate_type varchar(50) not null,
    aggregate_id   varchar(50) not null,
    event_type     varchar(50) not null,
    payload        text        not null,
    occurred_at    timestamptz not null,
    published      boolean     not null default false
);

-- Partial index: the relay only ever scans unpublished rows.
create index idx_outbox_unpublished on outbox (id) where published = false;