create table comment
(
    id         bigint generated by default as identity primary key,
    ticket_id  bigint       not null,
    author_id  varchar(100) not null,
    body       text         not null,
    created_at timestamptz  not null
);

create index idx_comment_ticket on comment (ticket_id, created_at);
